Fix #724: Remove filter flag constants deprecated as of PHP 7.3
Error messages:
    Fatal error: Uncaught Error: Undefined constant "FILTER_FLAG_SCHEME_REQUIRED" in [...]
    Fatal error: Uncaught Error: Undefined constant "FILTER_FLAG_HOST_REQUIRED" in [...]