Fix continuous integration tests for PHP 7.3.
There were 3 errors:
    1) CurlTest\CurlTest::testMultipartFormDataContentType
    TypeError: Argument 2 passed to PHPUnit\Framework\Assert::assertContains() must be iterable, string given, [...]

    2) CurlTest\CurlTest::testJsonEncode
    ErrorException: json_encode error: Malformed UTF-8 characters, possibly incorrectly encoded

    3) CurlTest\CurlTest::testRequiredOptionCurlOptReturnTransferEmitsWarning
    CURLOPT_RETURNTRANSFER is a required option